# Generated by Django 3.0.5 on 2020-04-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference',
        ),
    ]
